$:.push File.expand_path("../ecore", __FILE__)
require 'version'
require 'document'
require 'repository'
require 'model_resource'
require 'document_resource'
require 'link'
require 'label'
require 'user'
require 'group'
require 'audit'
